// <auto-generated />
using System;
using System.Collections.Generic;
using AnuncieCompre.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnuncieCompre.Migrations
{
    [DbContext(typeof(AnuncieCompreContext))]
    [Migration("20260726231002_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnuncieCompre.Domain.Aggregates.ConversationAggregate.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attendant")
                        .HasColumnType("integer");

                    b.Property<string>("AwaitingResponseNodeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTimeLastMessage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsProcessing")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "User", "AnuncieCompre.Domain.Aggregates.ConversationAggregate.Conversation.User#User", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Email", "AnuncieCompre.Domain.Aggregates.ConversationAggregate.Conversation.User#User.Email#Email", b2 =>
                                {
                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Name", "AnuncieCompre.Domain.Aggregates.ConversationAggregate.Conversation.User#User.Name#Name", b2 =>
                                {
                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Phone", "AnuncieCompre.Domain.Aggregates.ConversationAggregate.Conversation.User#User.Phone#Phone", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });
                        });

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("AnuncieCompre.Domain.Aggregates.MessageAggregate.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<int>("SenderType")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Conversation", "AnuncieCompre.Domain.Aggregates.MessageAggregate.Message.Conversation#Conversation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Attendant")
                                .HasColumnType("integer");

                            b1.Property<string>("AwaitingResponseNodeId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("DateTimeLastMessage")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("EndedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsProcessing")
                                .HasColumnType("boolean");

                            b1.Property<int>("Status")
                                .HasColumnType("integer");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "User", "AnuncieCompre.Domain.Aggregates.MessageAggregate.Message.Conversation#Conversation.User#User", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Email", "AnuncieCompre.Domain.Aggregates.MessageAggregate.Message.Conversation#Conversation.User#User.Email#Email", b3 =>
                                        {
                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasColumnType("text");
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Name", "AnuncieCompre.Domain.Aggregates.MessageAggregate.Message.Conversation#Conversation.User#User.Name#Name", b3 =>
                                        {
                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasColumnType("text");
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Phone", "AnuncieCompre.Domain.Aggregates.MessageAggregate.Message.Conversation#Conversation.User#User.Phone#Phone", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasColumnType("text");
                                        });
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("AnuncieCompre.Domain.Aggregates.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Category", "AnuncieCompre.Domain.Aggregates.OrderAggregate.Order.Category#CompanyCategory", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("integer");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Product", "AnuncieCompre.Domain.Aggregates.OrderAggregate.Order.Product#Product", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Quantity", "AnuncieCompre.Domain.Aggregates.OrderAggregate.Order.Quantity#Quantity", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AnuncieCompre.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "AnuncieCompre.Domain.Aggregates.UserAggregate.User.Email#Email", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "AnuncieCompre.Domain.Aggregates.UserAggregate.User.Name#Name", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Phone", "AnuncieCompre.Domain.Aggregates.UserAggregate.User.Phone#Phone", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AnuncieCompre.Domain.Aggregates.MessageAggregate.Message", b =>
                {
                    b.HasOne("AnuncieCompre.Domain.Aggregates.ConversationAggregate.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnuncieCompre.Domain.Aggregates.OrderAggregate.Order", b =>
                {
                    b.HasOne("AnuncieCompre.Domain.Aggregates.UserAggregate.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnuncieCompre.Domain.Aggregates.ConversationAggregate.Conversation", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
